<?php

namespace FrontendBundle\Repository;

/**
 * ObraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObraRepository extends \Doctrine\ORM\EntityRepository
{
}
