<?php

namespace FrontendBundle\Repository;

/**
 * TipoObraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoObraRepository extends \Doctrine\ORM\EntityRepository
{
}
